### ISSUE TITLE
Problems after de-install

### ISSUE THREAD

**Issue by pibroens** [trustmaster/cot-hybridauth#1]
After a de-install, plugin is not really de-installed. You don't get the option to install, only update, pause, ...
But the plugin is not working, like it should.

If you click update, it still doesn't work. And the tags are visible on the site and not the output of it.

I solved it by restoring the database.

**Comment by trustmaster** [comment]
For some weird reason the loop in the uninstall part halts the script, seems like a PHP bug. I solved it by disabling that loop for now.
